/**
 * Canonical default metric list for SimplySG platform companies.
 *
 * This is the single source of truth for the 28 default metrics every company
 * receives on onboarding. Import from here — do NOT copy this list elsewhere.
 *
 * Consumers:
 *   server/routes.ts          – seedDatabase() and seedMetricsFromSelection()
 *   server/seed-pe-demo.ts    – demo company metric seeding
 */

export interface DefaultMetric {
  name: string;
  description: string;
  category: "environmental" | "social" | "governance";
  unit: string;
  frequency: "monthly" | "quarterly" | "annual";
  dataOwner: string;
  metricType: string;
  direction: string;
  displayOrder: number;
  helpText: string;
  calculationType?: string | null;
  formulaText?: string;
  targetMin?: string;
  targetMax?: string;
}

export const DEFAULT_METRICS: DefaultMetric[] = [
  // ── Environmental (10) ──────────────────────────────────────────────────────
  {
    name: "Electricity Consumption",
    description: "Total electricity used across all sites",
    category: "environmental",
    unit: "kWh",
    frequency: "monthly",
    dataOwner: "Operations Manager",
    metricType: "manual",
    direction: "lower_is_better",
    displayOrder: 1,
    helpText: "Enter your total electricity usage in kilowatt-hours from your utility bills",
  },
  {
    name: "Gas / Fuel Consumption",
    description: "Natural gas and fuel oil consumption",
    category: "environmental",
    unit: "kWh",
    frequency: "monthly",
    dataOwner: "Operations Manager",
    metricType: "manual",
    direction: "lower_is_better",
    displayOrder: 2,
    helpText: "Enter gas consumption in kWh from your gas bills",
  },
  {
    name: "Company Vehicle Fuel Use",
    description: "Total fuel used by company-owned or leased vehicles",
    category: "environmental",
    unit: "litres",
    frequency: "monthly",
    dataOwner: "Operations Manager",
    metricType: "manual",
    direction: "lower_is_better",
    displayOrder: 3,
    helpText: "Enter total fuel purchased for company vehicles in litres",
  },
  {
    name: "Scope 1 Emissions",
    description: "Direct greenhouse gas emissions from owned sources (gas, fuel, vehicles)",
    category: "environmental",
    unit: "tCO2e",
    frequency: "quarterly",
    dataOwner: "Operations Manager",
    metricType: "calculated",
    calculationType: "scope1",
    formulaText: "(Gas kWh × gas factor + Vehicle litres × fuel factor) / 1000",
    direction: "lower_is_better",
    displayOrder: 4,
    helpText: "Automatically calculated from your gas/fuel consumption and vehicle fuel data",
  },
  {
    name: "Scope 2 Emissions",
    description: "Indirect emissions from purchased electricity",
    category: "environmental",
    unit: "tCO2e",
    frequency: "quarterly",
    dataOwner: "Operations Manager",
    metricType: "calculated",
    calculationType: "scope2",
    formulaText: "Electricity kWh × electricity emission factor / 1000",
    direction: "lower_is_better",
    displayOrder: 5,
    helpText: "Automatically calculated from your electricity consumption",
  },
  {
    name: "Waste Generated",
    description: "Total waste produced by the business",
    category: "environmental",
    unit: "tonnes",
    frequency: "monthly",
    dataOwner: "Facilities Manager",
    metricType: "manual",
    direction: "lower_is_better",
    displayOrder: 6,
    helpText: "Enter total waste in tonnes from your waste collection records",
  },
  {
    name: "Recycling Rate",
    description: "Percentage of waste that is recycled",
    category: "environmental",
    unit: "%",
    frequency: "monthly",
    dataOwner: "Facilities Manager",
    metricType: "calculated",
    calculationType: "recycling_rate",
    formulaText: "Recycled waste / Total waste × 100",
    direction: "higher_is_better",
    displayOrder: 7,
    helpText: "Automatically calculated from waste and recycled waste data",
  },
  {
    name: "Water Consumption",
    description: "Total water used across all sites",
    category: "environmental",
    unit: "m³",
    frequency: "monthly",
    dataOwner: "Facilities Manager",
    metricType: "manual",
    direction: "lower_is_better",
    displayOrder: 8,
    helpText: "Enter water consumption in cubic metres from your water bills",
  },
  {
    name: "Business Travel Emissions",
    description: "Emissions from business travel including flights, rail, hotels, and car mileage",
    category: "environmental",
    unit: "tCO2e",
    frequency: "quarterly",
    dataOwner: "Operations Manager",
    metricType: "calculated",
    calculationType: "travel_emissions",
    formulaText: "Sum of (travel activity × emission factor) for each travel type / 1000",
    direction: "lower_is_better",
    displayOrder: 9,
    helpText: "Automatically calculated from your business travel activity data",
  },
  {
    name: "Carbon Intensity",
    description: "Total carbon emissions relative to business size (per employee or per £m revenue)",
    category: "environmental",
    unit: "tCO2e/employee",
    frequency: "quarterly",
    dataOwner: "Operations Manager",
    metricType: "derived",
    calculationType: "carbon_intensity",
    formulaText: "(Scope 1 + Scope 2 + Travel Emissions) / Total employees",
    direction: "lower_is_better",
    displayOrder: 10,
    helpText: "Derived from your total emissions and employee count or revenue",
  },
  // ── Social (10) ─────────────────────────────────────────────────────────────
  {
    name: "Total Employees",
    description: "Total number of employees (headcount)",
    category: "social",
    unit: "people",
    frequency: "monthly",
    dataOwner: "HR Manager",
    metricType: "manual",
    direction: "higher_is_better",
    displayOrder: 11,
    helpText: "Enter your total employee headcount",
  },
  {
    name: "Gender Split (% Female)",
    description: "Percentage of workforce identifying as female",
    category: "social",
    unit: "%",
    frequency: "quarterly",
    dataOwner: "HR Manager",
    metricType: "manual",
    direction: "target_range",
    targetMin: "40",
    targetMax: "60",
    displayOrder: 12,
    helpText: "Enter the percentage of your workforce identifying as female",
  },
  {
    name: "Management Gender Diversity",
    description: "Percentage of management positions held by women",
    category: "social",
    unit: "%",
    frequency: "quarterly",
    dataOwner: "HR Manager",
    metricType: "calculated",
    calculationType: "management_diversity",
    formulaText: "Female managers / Total managers × 100",
    direction: "target_range",
    targetMin: "30",
    targetMax: "60",
    displayOrder: 13,
    helpText: "Calculated from female managers and total managers data",
  },
  {
    name: "Employee Turnover Rate",
    description: "Employees leaving as a percentage of average headcount",
    category: "social",
    unit: "%",
    frequency: "quarterly",
    dataOwner: "HR Manager",
    metricType: "calculated",
    calculationType: "turnover_rate",
    formulaText: "Employee leavers / Average headcount × 100",
    direction: "lower_is_better",
    displayOrder: 14,
    helpText: "Calculated from leavers and headcount data",
  },
  {
    name: "Absence Rate",
    description: "Employee absence as a percentage of total working days",
    category: "social",
    unit: "%",
    frequency: "monthly",
    dataOwner: "HR Manager",
    metricType: "calculated",
    calculationType: "absence_rate",
    formulaText: "Absence days / Total working days × 100",
    direction: "lower_is_better",
    displayOrder: 15,
    helpText: "Calculated from absence days and total working days",
  },
  {
    name: "Training Hours per Employee",
    description: "Average training hours delivered per employee",
    category: "social",
    unit: "hours",
    frequency: "quarterly",
    dataOwner: "HR Manager",
    metricType: "calculated",
    calculationType: "training_per_employee",
    formulaText: "Total training hours / Total employees",
    direction: "higher_is_better",
    displayOrder: 16,
    helpText: "Calculated from total training hours and headcount",
  },
  {
    name: "Lost Time Incidents",
    description: "Number of workplace incidents resulting in lost time",
    category: "social",
    unit: "incidents",
    frequency: "monthly",
    dataOwner: "H&S Manager",
    metricType: "manual",
    direction: "lower_is_better",
    displayOrder: 17,
    helpText: "Enter the number of incidents that resulted in time off work",
  },
  {
    name: "Employee Engagement Score",
    description: "Average employee engagement survey score",
    category: "social",
    unit: "score /10",
    frequency: "annual",
    dataOwner: "HR Manager",
    metricType: "manual",
    direction: "higher_is_better",
    displayOrder: 18,
    helpText: "Enter your latest employee engagement survey score (out of 10)",
  },
  {
    name: "Living Wage Coverage",
    description: "Percentage of employees paid at or above the real living wage",
    category: "social",
    unit: "%",
    frequency: "annual",
    dataOwner: "HR Manager",
    metricType: "calculated",
    calculationType: "living_wage",
    formulaText: "Employees paid living wage / Total employees × 100",
    direction: "higher_is_better",
    displayOrder: 19,
    helpText: "Calculated from living wage employee count and total headcount",
  },
  {
    name: "Community Investment",
    description: "Total value of community investment, donations, and volunteering",
    category: "social",
    unit: "£",
    frequency: "quarterly",
    dataOwner: "HR Manager",
    metricType: "manual",
    direction: "higher_is_better",
    displayOrder: 20,
    helpText: "Enter the total value of donations, sponsorship, and volunteering time",
  },
  // ── Governance (8) ──────────────────────────────────────────────────────────
  {
    name: "Board Meetings Held",
    description: "Number of board or senior management meetings held",
    category: "governance",
    unit: "meetings",
    frequency: "quarterly",
    dataOwner: "Company Secretary",
    metricType: "manual",
    direction: "target_range",
    targetMin: "4",
    targetMax: "12",
    displayOrder: 21,
    helpText: "Enter the number of board or senior management meetings this period",
  },
  {
    name: "Anti-Bribery Policy in Place",
    description: "Whether a formal anti-bribery and corruption policy exists",
    category: "governance",
    unit: "yes/no",
    frequency: "annual",
    dataOwner: "Compliance Manager",
    metricType: "manual",
    direction: "compliance_yes_no",
    displayOrder: 22,
    helpText: "Enter 1 if you have a policy in place, 0 if not",
  },
  {
    name: "Whistleblowing Policy in Place",
    description: "Whether a formal whistleblowing policy exists",
    category: "governance",
    unit: "yes/no",
    frequency: "annual",
    dataOwner: "Compliance Manager",
    metricType: "manual",
    direction: "compliance_yes_no",
    displayOrder: 23,
    helpText: "Enter 1 if you have a policy in place, 0 if not",
  },
  {
    name: "Data Privacy Training Completion",
    description: "Percentage of staff who completed data privacy training",
    category: "governance",
    unit: "%",
    frequency: "annual",
    dataOwner: "Data Protection Officer",
    metricType: "calculated",
    calculationType: "privacy_training",
    formulaText: "Trained staff / Total staff × 100",
    direction: "higher_is_better",
    displayOrder: 24,
    helpText: "Calculated from trained staff count and total staff",
  },
  {
    name: "Supplier Code of Conduct Adoption",
    description: "Percentage of suppliers who signed the code of conduct",
    category: "governance",
    unit: "%",
    frequency: "annual",
    dataOwner: "Procurement Manager",
    metricType: "calculated",
    calculationType: "supplier_code",
    formulaText: "Signed suppliers / Total suppliers × 100",
    direction: "higher_is_better",
    displayOrder: 25,
    helpText: "Calculated from signed and total supplier counts",
  },
  {
    name: "Cybersecurity Policy in Place",
    description: "Whether a formal cybersecurity policy exists",
    category: "governance",
    unit: "yes/no",
    frequency: "annual",
    dataOwner: "IT Manager",
    metricType: "manual",
    direction: "compliance_yes_no",
    displayOrder: 26,
    helpText: "Enter 1 if you have a policy in place, 0 if not",
  },
  {
    name: "ESG Responsibility Assigned",
    description: "Whether a named individual is responsible for ESG management",
    category: "governance",
    unit: "yes/no",
    frequency: "annual",
    dataOwner: "Managing Director",
    metricType: "manual",
    direction: "compliance_yes_no",
    displayOrder: 27,
    helpText: "Enter 1 if ESG responsibility is formally assigned, 0 if not",
  },
  {
    name: "ESG Targets Set",
    description: "Whether formal ESG targets have been established",
    category: "governance",
    unit: "yes/no",
    frequency: "annual",
    dataOwner: "Managing Director",
    metricType: "manual",
    direction: "compliance_yes_no",
    displayOrder: 28,
    helpText: "Enter 1 if formal ESG targets are set, 0 if not",
  },
];

export const DEFAULT_METRIC_NAMES = DEFAULT_METRICS.map((m) => m.name);
