import type { InsertMetricDefinition } from "@shared/schema";

export const CORE_METRIC_DEFINITIONS: Omit<InsertMetricDefinition, "createdAt" | "updatedAt">[] = [
  // ENVIRONMENTAL - Energy
  {
    code: "ENV_ELEC_KWH",
    name: "Electricity Consumption",
    pillar: "environmental",
    category: "Energy",
    description: "Total electricity consumed across all sites",
    dataType: "numeric",
    unit: "kWh",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GHG_PROTOCOL", "GRI_302"],
    scoringWeight: "1",
    sortOrder: 1,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "ENV_GAS_KWH",
    name: "Natural Gas Consumption",
    pillar: "environmental",
    category: "Energy",
    description: "Natural gas and fuel oil consumed for heating and operations",
    dataType: "numeric",
    unit: "kWh",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GHG_PROTOCOL", "GRI_302"],
    scoringWeight: "1",
    sortOrder: 2,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "ENV_VEHICLE_FUEL_L",
    name: "Company Vehicle Fuel Use",
    pillar: "environmental",
    category: "Energy",
    description: "Total fuel used by company-owned or leased vehicles",
    dataType: "numeric",
    unit: "litres",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GHG_PROTOCOL"],
    scoringWeight: "1",
    sortOrder: 3,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  // ENVIRONMENTAL - Emissions
  {
    code: "ENV_SCOPE1_TCO2E",
    name: "Scope 1 Emissions",
    pillar: "environmental",
    category: "Emissions",
    description: "Direct greenhouse gas emissions from owned sources (gas, fuel, vehicles)",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: {
      type: "expression",
      sources: ["ENV_GAS_KWH", "ENV_VEHICLE_FUEL_L"],
      expression: "(ENV_GAS_KWH * 0.18293 + ENV_VEHICLE_FUEL_L * 2.70559) / 1000",
      description: "(Gas kWh × gas factor + Vehicle litres × fuel factor) / 1000",
    },
    frameworkTags: ["GHG_PROTOCOL", "GRI_305"],
    scoringWeight: "2",
    sortOrder: 4,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "ENV_SCOPE2_TCO2E",
    name: "Scope 2 Emissions",
    pillar: "environmental",
    category: "Emissions",
    description: "Indirect emissions from purchased electricity",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: {
      type: "expression",
      sources: ["ENV_ELEC_KWH"],
      expression: "ENV_ELEC_KWH * 0.20707 / 1000",
      description: "Electricity kWh × emission factor / 1000",
    },
    frameworkTags: ["GHG_PROTOCOL", "GRI_305"],
    scoringWeight: "2",
    sortOrder: 5,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "ENV_TRAVEL_TCO2E",
    name: "Business Travel Emissions",
    pillar: "environmental",
    category: "Emissions",
    description: "Emissions from business travel including flights, rail, hotels, and car mileage",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GHG_PROTOCOL", "GRI_305"],
    scoringWeight: "1",
    sortOrder: 6,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "ENV_CARBON_INTENSITY",
    name: "Carbon Intensity",
    pillar: "environmental",
    category: "Emissions",
    description: "Total emissions relative to business size (per employee)",
    dataType: "numeric",
    unit: "tCO2e/employee",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: {
      type: "ratio",
      numerator: ["ENV_SCOPE1_TCO2E", "ENV_SCOPE2_TCO2E", "ENV_TRAVEL_TCO2E"],
      denominator: "SOC_HEADCOUNT",
      description: "(Scope 1 + Scope 2 + Travel) / Total employees",
    },
    frameworkTags: ["GHG_PROTOCOL", "GRI_305"],
    scoringWeight: "1",
    sortOrder: 7,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  // ENVIRONMENTAL - Waste
  {
    code: "ENV_WASTE_TOTAL_T",
    name: "Waste Generated",
    pillar: "environmental",
    category: "Waste",
    description: "Total waste produced by the business",
    dataType: "numeric",
    unit: "tonnes",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_306"],
    scoringWeight: "1",
    sortOrder: 8,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "ENV_WASTE_RECYCLED_T",
    name: "Recycled Waste",
    pillar: "environmental",
    category: "Waste",
    description: "Amount of waste sent for recycling",
    dataType: "numeric",
    unit: "tonnes",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_306"],
    scoringWeight: "1",
    sortOrder: 9,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "ENV_RECYCLING_RATE",
    name: "Recycling Rate",
    pillar: "environmental",
    category: "Waste",
    description: "Percentage of waste that is recycled",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: {
      type: "ratio",
      numerator: ["ENV_WASTE_RECYCLED_T"],
      denominator: "ENV_WASTE_TOTAL_T",
      scale: 100,
      description: "Recycled waste / Total waste × 100",
    },
    frameworkTags: ["GRI_306"],
    scoringWeight: "1",
    sortOrder: 10,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  // ENVIRONMENTAL - Water
  {
    code: "ENV_WATER_M3",
    name: "Water Consumption",
    pillar: "environmental",
    category: "Water",
    description: "Total water used across all sites",
    dataType: "numeric",
    unit: "m³",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_303"],
    scoringWeight: "1",
    sortOrder: 11,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  // SOCIAL - Workforce
  {
    code: "SOC_HEADCOUNT",
    name: "Total Employees",
    pillar: "social",
    category: "Workforce",
    description: "Total number of employees (headcount)",
    dataType: "numeric",
    unit: "people",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_401"],
    scoringWeight: "1",
    sortOrder: 12,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "SOC_GENDER_FEMALE_PCT",
    name: "Gender Split (% Female)",
    pillar: "social",
    category: "Diversity & Inclusion",
    description: "Percentage of workforce identifying as female",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_405"],
    scoringWeight: "1",
    sortOrder: 13,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "SOC_MGMT_GENDER_FEMALE_PCT",
    name: "Management Gender Diversity",
    pillar: "social",
    category: "Diversity & Inclusion",
    description: "Percentage of management positions held by women",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_405"],
    scoringWeight: "1",
    sortOrder: 14,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "SOC_TURNOVER_RATE",
    name: "Employee Turnover Rate",
    pillar: "social",
    category: "Workforce",
    description: "Employees leaving as a percentage of average headcount",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_401"],
    scoringWeight: "1",
    sortOrder: 15,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "SOC_ABSENCE_RATE",
    name: "Absence Rate",
    pillar: "social",
    category: "Workforce",
    description: "Employee absence as a percentage of total working days",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_403"],
    scoringWeight: "1",
    sortOrder: 16,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  // SOCIAL - Training & Development
  {
    code: "SOC_TRAINING_HRS_PER_EMP",
    name: "Training Hours per Employee",
    pillar: "social",
    category: "Training & Development",
    description: "Average training hours per employee per period",
    dataType: "numeric",
    unit: "hours",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_404"],
    scoringWeight: "1",
    sortOrder: 17,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  // SOCIAL - Health & Safety
  {
    code: "SOC_LTI_COUNT",
    name: "Lost Time Incidents",
    pillar: "social",
    category: "Health & Safety",
    description: "Number of workplace incidents resulting in lost time",
    dataType: "numeric",
    unit: "incidents",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_403"],
    scoringWeight: "1",
    sortOrder: 18,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "SOC_ENGAGEMENT_SCORE",
    name: "Employee Engagement Score",
    pillar: "social",
    category: "Workforce",
    description: "Employee engagement survey score out of 10",
    dataType: "numeric",
    unit: "score /10",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_401"],
    scoringWeight: "1",
    sortOrder: 19,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "SOC_LIVING_WAGE_PCT",
    name: "Living Wage Coverage",
    pillar: "social",
    category: "Workforce",
    description: "Percentage of employees paid at or above the living wage",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_202"],
    scoringWeight: "1",
    sortOrder: 20,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "SOC_COMMUNITY_INVEST_GBP",
    name: "Community Investment",
    pillar: "social",
    category: "Community",
    description: "Total investment in community initiatives",
    dataType: "numeric",
    unit: "£",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_413"],
    scoringWeight: "1",
    sortOrder: 21,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  // GOVERNANCE
  {
    code: "GOV_BOARD_MEETINGS",
    name: "Board Meetings Held",
    pillar: "governance",
    category: "Governance Structure",
    description: "Number of board or senior management meetings in the period",
    dataType: "numeric",
    unit: "meetings",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_405"],
    scoringWeight: "1",
    sortOrder: 22,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "GOV_ANTI_BRIBERY_POLICY",
    name: "Anti-Bribery Policy in Place",
    pillar: "governance",
    category: "Ethics & Compliance",
    description: "Whether a formal anti-bribery and corruption policy exists",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_205"],
    scoringWeight: "1",
    sortOrder: 23,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "GOV_WHISTLEBLOWING_POLICY",
    name: "Whistleblowing Policy in Place",
    pillar: "governance",
    category: "Ethics & Compliance",
    description: "Whether a formal whistleblowing/speak-up policy exists",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_406"],
    scoringWeight: "1",
    sortOrder: 24,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "GOV_DATA_PRIVACY_TRAINING_PCT",
    name: "Data Privacy Training Completion",
    pillar: "governance",
    category: "Data & Privacy",
    description: "Percentage of staff who have completed data privacy training",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_418"],
    scoringWeight: "1",
    sortOrder: 25,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "GOV_SUPPLIER_CODE_PCT",
    name: "Supplier Code of Conduct Adoption",
    pillar: "governance",
    category: "Supply Chain",
    description: "Percentage of suppliers who have signed the code of conduct",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_308", "GRI_414"],
    scoringWeight: "1",
    sortOrder: 26,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "GOV_CYBERSECURITY_POLICY",
    name: "Cybersecurity Policy in Place",
    pillar: "governance",
    category: "Data & Privacy",
    description: "Whether a formal cybersecurity policy exists",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_418"],
    scoringWeight: "1",
    sortOrder: 27,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "GOV_ESG_RESPONSIBILITY",
    name: "ESG Responsibility Assigned",
    pillar: "governance",
    category: "Governance Structure",
    description: "Whether ESG ownership has been formally assigned to a role or individual",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_2"],
    scoringWeight: "1",
    sortOrder: 28,
    evidenceRequired: false,
    rollupMethod: "none",
  },
];

export const ADVANCED_METRIC_DEFINITIONS: Omit<InsertMetricDefinition, "createdAt" | "updatedAt">[] = [
  // ENVIRONMENTAL - Advanced Energy
  {
    code: "ENV_RENEWABLE_ENERGY_PCT",
    name: "Renewable Energy Share",
    pillar: "environmental",
    category: "Energy",
    description: "Percentage of energy consumption from renewable sources",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "quarterly",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_302", "TCFD"],
    scoringWeight: "1",
    sortOrder: 100,
    evidenceRequired: true,
    rollupMethod: "weighted_average",
  },
  {
    code: "ENV_ENERGY_INTENSITY",
    name: "Energy Intensity",
    pillar: "environmental",
    category: "Energy",
    description: "Total energy consumption per employee or per £m revenue",
    dataType: "numeric",
    unit: "kWh/employee",
    inputFrequency: "quarterly",
    isCore: false,
    isActive: false,
    isDerived: true,
    formulaJson: {
      type: "ratio",
      numerator: ["ENV_ELEC_KWH", "ENV_GAS_KWH"],
      denominator: "SOC_HEADCOUNT",
      description: "(Electricity + Gas kWh) / Employees",
    },
    frameworkTags: ["GRI_302"],
    scoringWeight: "1",
    sortOrder: 101,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "ENV_SCOPE3_SUPPLY_TCO2E",
    name: "Scope 3 Supply Chain Emissions",
    pillar: "environmental",
    category: "Emissions",
    description: "Estimated upstream supply chain greenhouse gas emissions",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GHG_PROTOCOL", "GRI_305"],
    scoringWeight: "1",
    sortOrder: 102,
    evidenceRequired: true,
    rollupMethod: "sum",
  },
  {
    code: "ENV_SCOPE3_COMMUTE_TCO2E",
    name: "Scope 3 Employee Commuting Emissions",
    pillar: "environmental",
    category: "Emissions",
    description: "Estimated GHG emissions from employee commuting",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GHG_PROTOCOL"],
    scoringWeight: "1",
    sortOrder: 103,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "ENV_BIODIVERSITY_IMPACT",
    name: "Biodiversity Impact Assessment",
    pillar: "environmental",
    category: "Biodiversity",
    description: "Whether a biodiversity impact assessment has been completed",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_304", "TNFD"],
    scoringWeight: "1",
    sortOrder: 104,
    evidenceRequired: true,
    rollupMethod: "none",
  },
  {
    code: "ENV_WATER_RECYCLED_M3",
    name: "Water Recycled / Reused",
    pillar: "environmental",
    category: "Water",
    description: "Volume of water recycled or reused in operations",
    dataType: "numeric",
    unit: "m³",
    inputFrequency: "quarterly",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_303"],
    scoringWeight: "1",
    sortOrder: 105,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "ENV_WASTE_LANDFILL_T",
    name: "Waste to Landfill",
    pillar: "environmental",
    category: "Waste",
    description: "Amount of waste sent to landfill",
    dataType: "numeric",
    unit: "tonnes",
    inputFrequency: "monthly",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_306"],
    scoringWeight: "1",
    sortOrder: 106,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "ENV_HAZARDOUS_WASTE_T",
    name: "Hazardous Waste Generated",
    pillar: "environmental",
    category: "Waste",
    description: "Total hazardous waste produced",
    dataType: "numeric",
    unit: "tonnes",
    inputFrequency: "quarterly",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_306"],
    scoringWeight: "1",
    sortOrder: 107,
    evidenceRequired: true,
    rollupMethod: "sum",
  },
  {
    code: "ENV_NET_ZERO_TARGET",
    name: "Net Zero Target Committed",
    pillar: "environmental",
    category: "Climate Strategy",
    description: "Whether the business has committed to a net zero target with a defined year",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["TCFD", "SBTi"],
    scoringWeight: "2",
    sortOrder: 108,
    evidenceRequired: true,
    rollupMethod: "none",
  },
  {
    code: "ENV_CLIMATE_RISK_ASSESSED",
    name: "Climate Risk Assessment Completed",
    pillar: "environmental",
    category: "Climate Strategy",
    description: "Whether a formal climate-related risk and opportunity assessment has been conducted",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["TCFD"],
    scoringWeight: "1",
    sortOrder: 109,
    evidenceRequired: true,
    rollupMethod: "none",
  },
  // SOCIAL - Advanced
  {
    code: "SOC_DISABILITY_INCLUSION_PCT",
    name: "Disability Inclusion Rate",
    pillar: "social",
    category: "Diversity & Inclusion",
    description: "Percentage of employees who have disclosed a disability",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_405"],
    scoringWeight: "1",
    sortOrder: 110,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "SOC_ETHNICITY_DIVERSITY_PCT",
    name: "Ethnic Minority Representation",
    pillar: "social",
    category: "Diversity & Inclusion",
    description: "Percentage of workforce from ethnic minority backgrounds",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_405"],
    scoringWeight: "1",
    sortOrder: 111,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "SOC_GENDER_PAY_GAP_PCT",
    name: "Gender Pay Gap",
    pillar: "social",
    category: "Diversity & Inclusion",
    description: "Mean or median gender pay gap percentage",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_405"],
    scoringWeight: "1",
    sortOrder: 112,
    evidenceRequired: true,
    rollupMethod: "none",
  },
  {
    code: "SOC_PARENTAL_LEAVE_RETURN_PCT",
    name: "Parental Leave Return Rate",
    pillar: "social",
    category: "Workforce",
    description: "Percentage of employees returning to work after parental leave",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_401"],
    scoringWeight: "1",
    sortOrder: 113,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "SOC_WELLBEING_PROGRAMME",
    name: "Employee Wellbeing Programme",
    pillar: "social",
    category: "Health & Safety",
    description: "Whether a formal employee wellbeing programme is in place",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_403"],
    scoringWeight: "1",
    sortOrder: 114,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "SOC_NEAR_MISS_COUNT",
    name: "Near Miss Incidents",
    pillar: "social",
    category: "Health & Safety",
    description: "Number of near miss safety incidents reported",
    dataType: "numeric",
    unit: "incidents",
    inputFrequency: "monthly",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_403"],
    scoringWeight: "1",
    sortOrder: 115,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "SOC_HUMAN_RIGHTS_TRAINING_PCT",
    name: "Human Rights Training Completion",
    pillar: "social",
    category: "Human Rights",
    description: "Percentage of staff who have completed human rights awareness training",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_412"],
    scoringWeight: "1",
    sortOrder: 116,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "SOC_MODERN_SLAVERY_STATEMENT",
    name: "Modern Slavery Statement Published",
    pillar: "social",
    category: "Human Rights",
    description: "Whether a modern slavery statement has been published",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_408", "GRI_409"],
    scoringWeight: "1",
    sortOrder: 117,
    evidenceRequired: true,
    rollupMethod: "none",
  },
  {
    code: "SOC_VOLUNTEER_HOURS",
    name: "Employee Volunteer Hours",
    pillar: "social",
    category: "Community",
    description: "Total hours employees volunteered during working time",
    dataType: "numeric",
    unit: "hours",
    inputFrequency: "quarterly",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_413"],
    scoringWeight: "1",
    sortOrder: 118,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "SOC_SUPPLY_CHAIN_AUDIT_PCT",
    name: "Supply Chain Social Audit Coverage",
    pillar: "social",
    category: "Supply Chain",
    description: "Percentage of key suppliers audited for social standards",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_414"],
    scoringWeight: "1",
    sortOrder: 119,
    evidenceRequired: true,
    rollupMethod: "none",
  },
  // GOVERNANCE - Advanced
  {
    code: "GOV_BOARD_DIVERSITY_PCT",
    name: "Board Gender Diversity",
    pillar: "governance",
    category: "Governance Structure",
    description: "Percentage of board positions held by women",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_405"],
    scoringWeight: "1",
    sortOrder: 120,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "GOV_ESG_REPORTING_FRAMEWORK",
    name: "ESG Reporting Framework Adopted",
    pillar: "governance",
    category: "ESG Strategy",
    description: "Whether the business reports against a recognised ESG framework (GRI, TCFD, etc.)",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_2"],
    scoringWeight: "2",
    sortOrder: 121,
    evidenceRequired: true,
    rollupMethod: "none",
  },
  {
    code: "GOV_EXECUTIVE_ESG_PAY_LINK",
    name: "ESG Linked to Executive Pay",
    pillar: "governance",
    category: "Governance Structure",
    description: "Whether executive remuneration is linked to ESG performance targets",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_2"],
    scoringWeight: "1",
    sortOrder: 122,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "GOV_TAX_TRANSPARENCY",
    name: "Tax Transparency Policy",
    pillar: "governance",
    category: "Ethics & Compliance",
    description: "Whether a tax transparency or responsible tax policy has been adopted",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_207"],
    scoringWeight: "1",
    sortOrder: 123,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "GOV_AUDIT_COMMITTEE",
    name: "Audit Committee in Place",
    pillar: "governance",
    category: "Governance Structure",
    description: "Whether an independent audit committee or equivalent is in place",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_2"],
    scoringWeight: "1",
    sortOrder: 124,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "GOV_POLITICAL_DONATIONS",
    name: "Political Donations Made",
    pillar: "governance",
    category: "Ethics & Compliance",
    description: "Whether the business made any political donations in the period",
    dataType: "boolean",
    unit: "yes/no",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_415"],
    scoringWeight: "1",
    sortOrder: 125,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "GOV_DATA_BREACHES_COUNT",
    name: "Confirmed Data Breaches",
    pillar: "governance",
    category: "Data & Privacy",
    description: "Number of confirmed personal data breaches reported to regulators",
    dataType: "numeric",
    unit: "breaches",
    inputFrequency: "quarterly",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_418"],
    scoringWeight: "1",
    sortOrder: 126,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "GOV_SUPPLIER_ESG_SCREENING_PCT",
    name: "Supplier ESG Screening Rate",
    pillar: "governance",
    category: "Supply Chain",
    description: "Percentage of new suppliers screened against ESG criteria",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_308", "GRI_414"],
    scoringWeight: "1",
    sortOrder: 127,
    evidenceRequired: false,
    rollupMethod: "none",
  },
  {
    code: "GOV_ETHICS_TRAINING_PCT",
    name: "Ethics & Compliance Training Completion",
    pillar: "governance",
    category: "Ethics & Compliance",
    description: "Percentage of staff who have completed ethics and compliance training",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_205"],
    scoringWeight: "1",
    sortOrder: 128,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "GOV_GRIEVANCE_RESOLVED_PCT",
    name: "Grievance Resolution Rate",
    pillar: "governance",
    category: "Ethics & Compliance",
    description: "Percentage of formal grievances resolved within the reporting period",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "quarterly",
    isCore: false,
    isActive: false,
    isDerived: false,
    formulaJson: null,
    frameworkTags: ["GRI_2"],
    scoringWeight: "1",
    sortOrder: 129,
    evidenceRequired: false,
    rollupMethod: "none",
  },
];

export const ALL_METRIC_DEFINITIONS = [...CORE_METRIC_DEFINITIONS, ...ADVANCED_METRIC_DEFINITIONS];
