import { db } from "./storage";
import { metricDefinitions } from "@shared/schema";
import { eq } from "drizzle-orm";

interface MetricSeed {
  code: string;
  name: string;
  pillar: string;
  category: string;
  description: string;
  dataType: string;
  unit?: string;
  inputFrequency: string;
  isCore: boolean;
  isActive: boolean;
  isDerived: boolean;
  formulaJson?: object;
  frameworkTags?: string[];
  scoringWeight?: string;
  sortOrder: number;
  evidenceRequired?: boolean;
  rollupMethod: string;
}

const METRIC_DEFINITIONS: MetricSeed[] = [
  // ── ENVIRONMENTAL – CORE (10) ──────────────────────────────────────────
  {
    code: "E001",
    name: "Electricity Consumption",
    pillar: "environmental",
    category: "energy",
    description: "Total electricity consumed from the grid during the reporting period.",
    dataType: "numeric",
    unit: "kWh",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GHG Protocol", "TCFD", "GRI 302"],
    scoringWeight: "1.5",
    sortOrder: 10,
    evidenceRequired: true,
    rollupMethod: "sum",
  },
  {
    code: "E002",
    name: "Natural Gas Consumption",
    pillar: "environmental",
    category: "energy",
    description: "Total natural gas consumed during the reporting period.",
    dataType: "numeric",
    unit: "kWh",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GHG Protocol", "GRI 302"],
    scoringWeight: "1.5",
    sortOrder: 20,
    evidenceRequired: true,
    rollupMethod: "sum",
  },
  {
    code: "E003",
    name: "Vehicle Fuel Consumption",
    pillar: "environmental",
    category: "transport",
    description: "Total fuel consumed by company-owned or leased vehicles.",
    dataType: "numeric",
    unit: "litres",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GHG Protocol", "GRI 305"],
    scoringWeight: "1",
    sortOrder: 30,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "E004",
    name: "Scope 1 Emissions",
    pillar: "environmental",
    category: "emissions",
    description: "Direct GHG emissions from owned or controlled sources (gas combustion + vehicle fuel).",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: { type: "custom", customFn: "scope1_emissions", inputs: ["E002", "E003"] },
    frameworkTags: ["GHG Protocol", "TCFD", "GRI 305-1"],
    scoringWeight: "2",
    sortOrder: 40,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "E005",
    name: "Scope 2 Emissions",
    pillar: "environmental",
    category: "emissions",
    description: "Indirect GHG emissions from consumption of purchased electricity.",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: { type: "custom", customFn: "scope2_emissions", inputs: ["E001"] },
    frameworkTags: ["GHG Protocol", "TCFD", "GRI 305-2"],
    scoringWeight: "2",
    sortOrder: 50,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "E006",
    name: "Total GHG Emissions",
    pillar: "environmental",
    category: "emissions",
    description: "Total Scope 1 + Scope 2 greenhouse gas emissions.",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: { type: "sum", inputs: ["E004", "E005"] },
    frameworkTags: ["GHG Protocol", "TCFD", "GRI 305"],
    scoringWeight: "2",
    sortOrder: 60,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "E007",
    name: "Total Waste Generated",
    pillar: "environmental",
    category: "waste",
    description: "Total weight of waste generated during the reporting period.",
    dataType: "numeric",
    unit: "tonnes",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 306"],
    scoringWeight: "1",
    sortOrder: 70,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "E008",
    name: "Waste Recycled",
    pillar: "environmental",
    category: "waste",
    description: "Total weight of waste diverted from landfill through recycling.",
    dataType: "numeric",
    unit: "tonnes",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 306"],
    scoringWeight: "1",
    sortOrder: 80,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "E009",
    name: "Recycling Rate",
    pillar: "environmental",
    category: "waste",
    description: "Percentage of total waste that is recycled.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: { type: "ratio", numerator: "E008", denominator: "E007", multiplier: 100 },
    frameworkTags: ["GRI 306"],
    scoringWeight: "1.5",
    sortOrder: 90,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "E010",
    name: "Total Water Consumption",
    pillar: "environmental",
    category: "water",
    description: "Total water withdrawn and consumed during the reporting period.",
    dataType: "numeric",
    unit: "m³",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 303"],
    scoringWeight: "1",
    sortOrder: 100,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  // ── SOCIAL – CORE (10) ────────────────────────────────────────────────
  {
    code: "S001",
    name: "Total Headcount",
    pillar: "social",
    category: "workforce",
    description: "Total number of employees at the end of the reporting period.",
    dataType: "numeric",
    unit: "employees",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 102-8", "GRI 401"],
    scoringWeight: "1",
    sortOrder: 110,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "S002",
    name: "Employee Leavers",
    pillar: "social",
    category: "workforce",
    description: "Number of employees who left the organisation during the period.",
    dataType: "numeric",
    unit: "employees",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 401"],
    scoringWeight: "1",
    sortOrder: 120,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "S003",
    name: "Employee Turnover Rate",
    pillar: "social",
    category: "workforce",
    description: "Percentage of employees who left the organisation during the period.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: { type: "ratio", numerator: "S002", denominator: "S001", multiplier: 100 },
    frameworkTags: ["GRI 401"],
    scoringWeight: "1.5",
    sortOrder: 130,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S004",
    name: "Total Absence Days",
    pillar: "social",
    category: "wellbeing",
    description: "Total number of employee absence days during the reporting period.",
    dataType: "numeric",
    unit: "days",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 403"],
    scoringWeight: "1",
    sortOrder: 140,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "S005",
    name: "Absence Rate",
    pillar: "social",
    category: "wellbeing",
    description: "Percentage of working days lost to absence.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "monthly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: { type: "custom", customFn: "absence_rate", inputs: ["S004", "S001"] },
    frameworkTags: ["GRI 403"],
    scoringWeight: "1",
    sortOrder: 150,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S006",
    name: "Total Training Hours",
    pillar: "social",
    category: "development",
    description: "Total hours of employee training delivered during the period.",
    dataType: "numeric",
    unit: "hours",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 404"],
    scoringWeight: "1",
    sortOrder: 160,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "S007",
    name: "Training Hours per Employee",
    pillar: "social",
    category: "development",
    description: "Average training hours per employee during the period.",
    dataType: "numeric",
    unit: "hours",
    inputFrequency: "quarterly",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: { type: "ratio", numerator: "S006", denominator: "S001" },
    frameworkTags: ["GRI 404"],
    scoringWeight: "1.5",
    sortOrder: 170,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S008",
    name: "Female Employees",
    pillar: "social",
    category: "diversity",
    description: "Percentage of employees who identify as female.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 405"],
    scoringWeight: "1.5",
    sortOrder: 180,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S009",
    name: "Lost Time Injury Rate",
    pillar: "social",
    category: "health_safety",
    description: "Number of lost time injuries per 100 employees per year.",
    dataType: "numeric",
    unit: "per 100 employees",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 403-9"],
    scoringWeight: "2",
    sortOrder: 190,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S010",
    name: "Pay Gap",
    pillar: "social",
    category: "diversity",
    description: "Mean gender pay gap as a percentage of male median salary.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 405-2"],
    scoringWeight: "1.5",
    sortOrder: 200,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  // ── GOVERNANCE – CORE (8) ─────────────────────────────────────────────
  {
    code: "G001",
    name: "Board Size",
    pillar: "governance",
    category: "board",
    description: "Total number of members on the board of directors.",
    dataType: "numeric",
    unit: "members",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 102-22"],
    scoringWeight: "1",
    sortOrder: 210,
    evidenceRequired: false,
    rollupMethod: "latest",
  },
  {
    code: "G002",
    name: "Female Board Members",
    pillar: "governance",
    category: "board",
    description: "Percentage of board members who identify as female.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 405-1"],
    scoringWeight: "1.5",
    sortOrder: 220,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "G003",
    name: "Independent Directors",
    pillar: "governance",
    category: "board",
    description: "Percentage of board members classified as independent non-executive directors.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 102-22"],
    scoringWeight: "1.5",
    sortOrder: 230,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "G004",
    name: "Data Privacy Training",
    pillar: "governance",
    category: "compliance",
    description: "Percentage of employees who have completed data privacy training.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 418"],
    scoringWeight: "1.5",
    sortOrder: 240,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "G005",
    name: "Anti-Corruption Training",
    pillar: "governance",
    category: "compliance",
    description: "Percentage of employees who have completed anti-corruption and ethics training.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 205"],
    scoringWeight: "1.5",
    sortOrder: 250,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "G006",
    name: "Supplier Code Adoption",
    pillar: "governance",
    category: "supply_chain",
    description: "Percentage of key suppliers who have signed the code of conduct.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 308", "GRI 414"],
    scoringWeight: "1",
    sortOrder: 260,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "G007",
    name: "Policy Review Completion",
    pillar: "governance",
    category: "compliance",
    description: "Percentage of scheduled policy reviews completed on time.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: false,
    frameworkTags: ["GRI 102"],
    scoringWeight: "1",
    sortOrder: 270,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "G008",
    name: "Carbon Intensity",
    pillar: "governance",
    category: "emissions",
    description: "Total GHG emissions per employee — a normalised efficiency measure.",
    dataType: "numeric",
    unit: "tCO2e/employee",
    inputFrequency: "annual",
    isCore: true,
    isActive: true,
    isDerived: true,
    formulaJson: { type: "ratio", numerator: "E006", denominator: "S001" },
    frameworkTags: ["TCFD", "GHG Protocol"],
    scoringWeight: "2",
    sortOrder: 280,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },

  // ── ENVIRONMENTAL – ADVANCED (10) ─────────────────────────────────────
  {
    code: "E011",
    name: "Renewable Energy Usage",
    pillar: "environmental",
    category: "energy",
    description: "Electricity consumed from certified renewable sources (solar, wind, etc.).",
    dataType: "numeric",
    unit: "kWh",
    inputFrequency: "monthly",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 302-1", "RE100"],
    scoringWeight: "1.5",
    sortOrder: 310,
    evidenceRequired: true,
    rollupMethod: "sum",
  },
  {
    code: "E012",
    name: "Renewable Energy Percentage",
    pillar: "environmental",
    category: "energy",
    description: "Renewable energy as a percentage of total electricity consumed.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "monthly",
    isCore: false,
    isActive: false,
    isDerived: true,
    formulaJson: { type: "ratio", numerator: "E011", denominator: "E001", multiplier: 100 },
    frameworkTags: ["GRI 302", "RE100"],
    scoringWeight: "2",
    sortOrder: 320,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "E013",
    name: "Scope 3 Emissions",
    pillar: "environmental",
    category: "emissions",
    description: "Indirect GHG emissions from the value chain (supply chain, business travel, waste, etc.).",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GHG Protocol", "GRI 305-3", "TCFD"],
    scoringWeight: "2",
    sortOrder: 330,
    evidenceRequired: true,
    rollupMethod: "sum",
  },
  {
    code: "E014",
    name: "Business Travel Emissions",
    pillar: "environmental",
    category: "transport",
    description: "GHG emissions from employee business travel (flights, rail, hotels, hire cars).",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "quarterly",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GHG Protocol", "GRI 305-3"],
    scoringWeight: "1.5",
    sortOrder: 340,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "E015",
    name: "Fleet EV Percentage",
    pillar: "environmental",
    category: "transport",
    description: "Percentage of company fleet vehicles that are fully electric.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["TCFD"],
    scoringWeight: "1",
    sortOrder: 350,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "E016",
    name: "Refrigerant Leakage",
    pillar: "environmental",
    category: "emissions",
    description: "GHG emissions from refrigerant gas leakage (F-gases).",
    dataType: "numeric",
    unit: "tCO2e",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GHG Protocol", "GRI 305-1"],
    scoringWeight: "1",
    sortOrder: 360,
    evidenceRequired: true,
    rollupMethod: "sum",
  },
  {
    code: "E017",
    name: "Biodiversity Impact Score",
    pillar: "environmental",
    category: "biodiversity",
    description: "Self-assessed score indicating biodiversity net gain or loss from operations.",
    dataType: "numeric",
    unit: "score",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["TNFD"],
    scoringWeight: "1",
    sortOrder: 370,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "E018",
    name: "Sustainable Packaging",
    pillar: "environmental",
    category: "waste",
    description: "Percentage of packaging materials that are recyclable, reusable or compostable.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 306"],
    scoringWeight: "1",
    sortOrder: 380,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "E019",
    name: "Water Intensity",
    pillar: "environmental",
    category: "water",
    description: "Water consumed per employee — a normalised water efficiency measure.",
    dataType: "numeric",
    unit: "m³/employee",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: true,
    formulaJson: { type: "ratio", numerator: "E010", denominator: "S001" },
    frameworkTags: ["GRI 303"],
    scoringWeight: "1",
    sortOrder: 390,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "E020",
    name: "Waste Intensity",
    pillar: "environmental",
    category: "waste",
    description: "Total waste generated per employee — a normalised waste efficiency measure.",
    dataType: "numeric",
    unit: "kg/employee",
    inputFrequency: "monthly",
    isCore: false,
    isActive: false,
    isDerived: true,
    formulaJson: { type: "ratio", numerator: "E007", denominator: "S001", multiplier: 1000 },
    frameworkTags: ["GRI 306"],
    scoringWeight: "1",
    sortOrder: 400,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },

  // ── SOCIAL – ADVANCED (10) ────────────────────────────────────────────
  {
    code: "S011",
    name: "Living Wage Coverage",
    pillar: "social",
    category: "pay_benefits",
    description: "Percentage of employees paid at or above the real living wage.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["Living Wage Foundation", "GRI 202"],
    scoringWeight: "1.5",
    sortOrder: 410,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S012",
    name: "Management Gender Diversity",
    pillar: "social",
    category: "diversity",
    description: "Percentage of managers who identify as female.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 405-1"],
    scoringWeight: "1.5",
    sortOrder: 420,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S013",
    name: "Parental Leave Take-up",
    pillar: "social",
    category: "wellbeing",
    description: "Percentage of eligible employees who took parental leave.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 401-3"],
    scoringWeight: "1",
    sortOrder: 430,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S014",
    name: "Employee Engagement Score",
    pillar: "social",
    category: "wellbeing",
    description: "Overall employee engagement score from the annual survey (0-100).",
    dataType: "numeric",
    unit: "score",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 401"],
    scoringWeight: "1.5",
    sortOrder: 440,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S015",
    name: "Disabled Employees",
    pillar: "social",
    category: "diversity",
    description: "Percentage of employees who have declared a disability.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 405-1"],
    scoringWeight: "1",
    sortOrder: 450,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S016",
    name: "Ethnically Diverse Employees",
    pillar: "social",
    category: "diversity",
    description: "Percentage of employees from ethnic minority backgrounds.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 405-1"],
    scoringWeight: "1",
    sortOrder: 460,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "S017",
    name: "Community Investment",
    pillar: "social",
    category: "community",
    description: "Total monetary value of contributions to community initiatives and charitable causes.",
    dataType: "numeric",
    unit: "£",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 413"],
    scoringWeight: "1",
    sortOrder: 470,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "S018",
    name: "Volunteering Hours",
    pillar: "social",
    category: "community",
    description: "Total employee volunteering hours contributed during the period.",
    dataType: "numeric",
    unit: "hours",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 413"],
    scoringWeight: "1",
    sortOrder: 480,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "S019",
    name: "Modern Slavery Checks",
    pillar: "social",
    category: "supply_chain",
    description: "Number of supplier due diligence checks completed for modern slavery risk.",
    dataType: "numeric",
    unit: "checks",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["Modern Slavery Act", "GRI 409"],
    scoringWeight: "1",
    sortOrder: 490,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "S020",
    name: "Human Rights Due Diligence",
    pillar: "social",
    category: "supply_chain",
    description: "Percentage of high-risk supplier relationships with completed human rights due diligence.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 412", "UN Guiding Principles"],
    scoringWeight: "1",
    sortOrder: 500,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },

  // ── GOVERNANCE – ADVANCED (10) ────────────────────────────────────────
  {
    code: "G009",
    name: "ESG Committee Meetings",
    pillar: "governance",
    category: "oversight",
    description: "Number of formal ESG or sustainability committee meetings held during the year.",
    dataType: "numeric",
    unit: "meetings",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 102-26"],
    scoringWeight: "1",
    sortOrder: 510,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "G010",
    name: "Whistleblowing Reports",
    pillar: "governance",
    category: "compliance",
    description: "Number of reports received through the whistleblowing mechanism.",
    dataType: "numeric",
    unit: "reports",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 102-17"],
    scoringWeight: "1",
    sortOrder: 520,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "G011",
    name: "Regulatory Fines",
    pillar: "governance",
    category: "compliance",
    description: "Number of regulatory fines or sanctions received during the period.",
    dataType: "numeric",
    unit: "count",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 307"],
    scoringWeight: "2",
    sortOrder: 530,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "G012",
    name: "Cybersecurity Incidents",
    pillar: "governance",
    category: "digital",
    description: "Number of significant cybersecurity incidents (breach attempts or confirmed incidents) in the period.",
    dataType: "numeric",
    unit: "incidents",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 418"],
    scoringWeight: "1.5",
    sortOrder: 540,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "G013",
    name: "Data Breaches",
    pillar: "governance",
    category: "digital",
    description: "Number of confirmed personal data breaches reported to regulators.",
    dataType: "numeric",
    unit: "breaches",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 418", "GDPR"],
    scoringWeight: "2",
    sortOrder: 550,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "G014",
    name: "Executive Pay Ratio",
    pillar: "governance",
    category: "pay_benefits",
    description: "Ratio of highest-paid executive remuneration to median employee remuneration.",
    dataType: "numeric",
    unit: "ratio",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 102-38"],
    scoringWeight: "1",
    sortOrder: 560,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "G015",
    name: "Shareholder Approval Rate",
    pillar: "governance",
    category: "oversight",
    description: "Average percentage shareholder approval across all AGM resolutions.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 102-27"],
    scoringWeight: "1",
    sortOrder: 570,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
  {
    code: "G016",
    name: "Political Donations",
    pillar: "governance",
    category: "compliance",
    description: "Total monetary value of political donations or contributions during the period.",
    dataType: "numeric",
    unit: "£",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 415"],
    scoringWeight: "1",
    sortOrder: 580,
    evidenceRequired: false,
    rollupMethod: "sum",
  },
  {
    code: "G017",
    name: "Third-party ESG Audit Score",
    pillar: "governance",
    category: "oversight",
    description: "Score received from an independent third-party ESG audit (0–100).",
    dataType: "numeric",
    unit: "score",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["ISO 14001", "ISO 45001"],
    scoringWeight: "2",
    sortOrder: 590,
    evidenceRequired: true,
    rollupMethod: "weighted_average",
  },
  {
    code: "G018",
    name: "Tax Effective Rate",
    pillar: "governance",
    category: "compliance",
    description: "Effective corporate tax rate paid as a percentage of pre-tax profit.",
    dataType: "numeric",
    unit: "%",
    inputFrequency: "annual",
    isCore: false,
    isActive: false,
    isDerived: false,
    frameworkTags: ["GRI 207"],
    scoringWeight: "1",
    sortOrder: 600,
    evidenceRequired: false,
    rollupMethod: "weighted_average",
  },
];

export async function seedMetricDefinitions() {
  let seeded = 0;
  let skipped = 0;
  for (const m of METRIC_DEFINITIONS) {
    const existing = await db.select({ id: metricDefinitions.id })
      .from(metricDefinitions)
      .where(eq(metricDefinitions.code, m.code))
      .limit(1);

    if (existing.length > 0) {
      skipped++;
      continue;
    }

    await db.insert(metricDefinitions).values({
      code: m.code,
      name: m.name,
      pillar: m.pillar,
      category: m.category,
      description: m.description,
      dataType: m.dataType,
      unit: m.unit,
      inputFrequency: m.inputFrequency,
      isCore: m.isCore,
      isActive: m.isActive,
      isDerived: m.isDerived,
      formulaJson: m.formulaJson || null,
      frameworkTags: m.frameworkTags || null,
      scoringWeight: m.scoringWeight || "1",
      sortOrder: m.sortOrder,
      evidenceRequired: m.evidenceRequired || false,
      rollupMethod: m.rollupMethod,
    });
    seeded++;
  }

  if (seeded > 0 || skipped === 0) {
    console.log(`[MetricDefs] Seeded ${seeded} metric definitions (${skipped} already existed)`);
  }
}
